Update ha-climate-control.ts
This adds argument conversion from strings to `Number`s to prevent an erroneous string concatenation instead of numerical addition in line 74 and prevent a subsequent `TypeError: e.toFixed is not a function` in line 70.